[programs.localnet]
unstake = "6KBz9djJAH3gRHscq9ujMpyZ5bCK9a27o3ybDtJLXowz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/test-*.ts --parallel"

[test.validator]
slots_per_epoch = "32"
