[package]
name = "unstake_interface"
version = "1.0.0"
edition = "2021"

[dependencies]
borsh = "^0.9.1"
solana-program = "~1.14"
thiserror = "^1.0"
num-derive = "^0.3"
num-traits = "^0.2"

[dependencies.serde]
optional = true
version = "^1.0"
